// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: developers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isDeveloper = `-- name: IsDeveloper :one
SELECT EXISTS (
  SELECT 1
  FROM developers
  WHERE uid = $1
    AND deleted_at IS NULL
) AS is_developer
`

func (q *Queries) IsDeveloper(ctx context.Context, uid string) (bool, error) {
	row := q.db.QueryRow(ctx, isDeveloper, uid)
	var is_developer bool
	err := row.Scan(&is_developer)
	return is_developer, err
}

const listDevelopers = `-- name: ListDevelopers :many
SELECT uid, email, added_at, deleted_at
FROM developers
WHERE deleted_at IS NULL
ORDER BY added_at DESC
`

func (q *Queries) ListDevelopers(ctx context.Context) ([]Developer, error) {
	rows, err := q.db.Query(ctx, listDevelopers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Developer
	for rows.Next() {
		var i Developer
		if err := rows.Scan(
			&i.Uid,
			&i.Email,
			&i.AddedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDeveloper = `-- name: SoftDeleteDeveloper :execrows
UPDATE developers
SET deleted_at = $2
WHERE uid = $1
  AND deleted_at IS NULL
`

type SoftDeleteDeveloperParams struct {
	Uid       string             `json:"uid"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) SoftDeleteDeveloper(ctx context.Context, arg SoftDeleteDeveloperParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDeveloper, arg.Uid, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDeveloper = `-- name: UpsertDeveloper :one
INSERT INTO developers (uid, email, added_at, deleted_at)
VALUES ($1, $2, $3, NULL)
ON CONFLICT (uid)
DO UPDATE SET
  email = EXCLUDED.email,
  deleted_at = NULL
RETURNING uid, email, added_at, deleted_at
`

type UpsertDeveloperParams struct {
	Uid     string             `json:"uid"`
	Email   string             `json:"email"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
}

func (q *Queries) UpsertDeveloper(ctx context.Context, arg UpsertDeveloperParams) (Developer, error) {
	row := q.db.QueryRow(ctx, upsertDeveloper, arg.Uid, arg.Email, arg.AddedAt)
	var i Developer
	err := row.Scan(
		&i.Uid,
		&i.Email,
		&i.AddedAt,
		&i.DeletedAt,
	)
	return i, err
}
