// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Developer struct {
	Uid       string             `json:"uid"`
	Email     string             `json:"email"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Link struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Url        string             `json:"url"`
	Title      string             `json:"title"`
	IsArchived bool               `json:"is_archived"`
	Summary    *string            `json:"summary"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type LinkTag struct {
	LinkID    string             `json:"link_id"`
	TagID     string             `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceLog struct {
	ID             string             `json:"id"`
	Action         string             `json:"action"`
	Reason         *string            `json:"reason"`
	PerformedBy    string             `json:"performed_by"`
	PerformedByUid string             `json:"performed_by_uid"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	PreviousStatus bool               `json:"previous_status"`
}

type MaintenanceStatus struct {
	ID                string             `json:"id"`
	IsMaintenanceMode bool               `json:"is_maintenance_mode"`
	Reason            *string            `json:"reason"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	StartedBy         *string            `json:"started_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TimelineEntry struct {
	ID        string             `json:"id"`
	LinkID    string             `json:"link_id"`
	Type      string             `json:"type"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          string             `json:"id"`
	Email       *string            `json:"email"`
	DisplayName *string            `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
