// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddLinkTag(ctx context.Context, arg AddLinkTagParams) error
	AddTimelineEntry(ctx context.Context, arg AddTimelineEntryParams) (TimelineEntry, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateMaintenanceLog(ctx context.Context, arg CreateMaintenanceLogParams) (MaintenanceLog, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteLink(ctx context.Context, arg DeleteLinkParams) (int64, error)
	DeleteTagByID(ctx context.Context, arg DeleteTagByIDParams) (int64, error)
	DeleteTimelineEntryByID(ctx context.Context, arg DeleteTimelineEntryByIDParams) (int64, error)
	GetLinkByID(ctx context.Context, arg GetLinkByIDParams) (Link, error)
	GetMaintenanceStatus(ctx context.Context) (MaintenanceStatus, error)
	GetTagByUserAndName(ctx context.Context, arg GetTagByUserAndNameParams) (Tag, error)
	IsDeveloper(ctx context.Context, uid string) (bool, error)
	IsLinkOwner(ctx context.Context, arg IsLinkOwnerParams) (bool, error)
	LinkExists(ctx context.Context, arg LinkExistsParams) (bool, error)
	ListDevelopers(ctx context.Context) ([]Developer, error)
	ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error)
	ListMaintenanceLogs(ctx context.Context, limit int32) ([]MaintenanceLog, error)
	ListTagNamesByLinkID(ctx context.Context, linkID string) ([]string, error)
	ListTagsByUser(ctx context.Context, userID string) ([]Tag, error)
	ListTimelineByLinkID(ctx context.Context, linkID string) ([]TimelineEntry, error)
	Ping(ctx context.Context) (int32, error)
	RemoveLinkTagByName(ctx context.Context, arg RemoveLinkTagByNameParams) (int64, error)
	SoftDeleteDeveloper(ctx context.Context, arg SoftDeleteDeveloperParams) (int64, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpsertDeveloper(ctx context.Context, arg UpsertDeveloperParams) (Developer, error)
	UpsertMaintenanceStatus(ctx context.Context, arg UpsertMaintenanceStatusParams) (MaintenanceStatus, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
