// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLinkTag = `-- name: AddLinkTag :exec
INSERT INTO link_tags (link_id, tag_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (link_id, tag_id) DO NOTHING
`

type AddLinkTagParams struct {
	LinkID    string             `json:"link_id"`
	TagID     string             `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddLinkTag(ctx context.Context, arg AddLinkTagParams) error {
	_, err := q.db.Exec(ctx, addLinkTag, arg.LinkID, arg.TagID, arg.CreatedAt)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, user_id, name, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, name)
DO UPDATE SET name = EXCLUDED.name
RETURNING id, user_id, name, created_at
`

type CreateTagParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTagByID = `-- name: DeleteTagByID :execrows
DELETE FROM tags
WHERE id = $1
  AND user_id = $2
`

type DeleteTagByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTagByID(ctx context.Context, arg DeleteTagByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTagByID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTagByUserAndName = `-- name: GetTagByUserAndName :one
SELECT id, user_id, name, created_at
FROM tags
WHERE user_id = $1
  AND name = $2
LIMIT 1
`

type GetTagByUserAndNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) GetTagByUserAndName(ctx context.Context, arg GetTagByUserAndNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByUserAndName, arg.UserID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listTagNamesByLinkID = `-- name: ListTagNamesByLinkID :many
SELECT t.name
FROM link_tags lt
INNER JOIN tags t ON t.id = lt.tag_id
WHERE lt.link_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTagNamesByLinkID(ctx context.Context, linkID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTagNamesByLinkID, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUser = `-- name: ListTagsByUser :many
SELECT id, user_id, name, created_at
FROM tags
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTagsByUser(ctx context.Context, userID string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLinkTagByName = `-- name: RemoveLinkTagByName :execrows
DELETE FROM link_tags lt
USING tags t, links l
WHERE lt.link_id = l.id
  AND lt.tag_id = t.id
  AND l.id = $1
  AND l.user_id = $2
  AND t.user_id = $2
  AND t.name = $3
`

type RemoveLinkTagByNameParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) RemoveLinkTagByName(ctx context.Context, arg RemoveLinkTagByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeLinkTagByName, arg.ID, arg.UserID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
