// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeline.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTimelineEntry = `-- name: AddTimelineEntry :one
INSERT INTO timeline_entries (id, link_id, type, content, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, link_id, type, content, created_at
`

type AddTimelineEntryParams struct {
	ID        string             `json:"id"`
	LinkID    string             `json:"link_id"`
	Type      string             `json:"type"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddTimelineEntry(ctx context.Context, arg AddTimelineEntryParams) (TimelineEntry, error) {
	row := q.db.QueryRow(ctx, addTimelineEntry,
		arg.ID,
		arg.LinkID,
		arg.Type,
		arg.Content,
		arg.CreatedAt,
	)
	var i TimelineEntry
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimelineEntryByID = `-- name: DeleteTimelineEntryByID :execrows
DELETE FROM timeline_entries te
USING links l
WHERE te.id = $1
  AND te.link_id = l.id
  AND l.id = $2
  AND l.user_id = $3
`

type DeleteTimelineEntryByIDParams struct {
	ID     string `json:"id"`
	ID_2   string `json:"id_2"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTimelineEntryByID(ctx context.Context, arg DeleteTimelineEntryByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimelineEntryByID, arg.ID, arg.ID_2, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTimelineByLinkID = `-- name: ListTimelineByLinkID :many
SELECT id, link_id, type, content, created_at
FROM timeline_entries
WHERE link_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTimelineByLinkID(ctx context.Context, linkID string) ([]TimelineEntry, error) {
	rows, err := q.db.Query(ctx, listTimelineByLinkID, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineEntry
	for rows.Next() {
		var i TimelineEntry
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
